### PR TITLE
PPMFoo->Foo. Fixed #116

### LINKED ISSUE #116: Drop "PPM" prefix for all protocol messages
Protocol messages are defined in the context of the PPM document, so the "PPM" seems redundant. I think we should just call things as they are, i.e., `TaskID` instead of `PPMTaskID`.

### PR DESCRIPTION
**Pull request by ekr**

### CODE REVIEW

**Review by cjpatton — CHANGES_REQUESTED** [review]
Yesterday I spotted an old "PA" prefix that was missed when we did s/PA/PDA/ would you mind finding it and fixing it?

**Review by chris-wood — APPROVED** [review]

**Comment by ekr** [comment]
@cjpatton I'm struggling with Github here and can't figure out what change you want.

**Review by cjpatton — APPROVED** [review]
Disregard, I found it and pushed myself.

**Comment by ekr** [comment]
Thanks.

**Pull request merged**
